AWSTemplateFormatVersion: '2010-09-09'
Description: Core infrastructure for file upload system

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  FileMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: FileName
          AttributeType: S
      KeySchema:
        - AttributeName: FileName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  UploadBucketName:
    Description: "Name of the S3 bucket for uploads"
    Value: !Ref UploadBucket
  FileMetadataTableName:
    Description: "Name of the DynamoDB table for metadata"
    Value: !Ref FileMetadataTable
