AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless application for storing file metadata in DynamoDB

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket

  FileMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: FileName
          AttributeType: S
      KeySchema:
        - AttributeName: FileName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FileMetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FileMetadataTable
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${UploadBucket}/*"
      Environment:
        Variables:
          TABLE_NAME: !Ref FileMetadataTable
          BUCKET_NAME: !Ref UploadBucket

  BucketNotificationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt FileMetadataFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt UploadBucket.Arn

Outputs:
  UploadBucketName:
    Description: "Name of the S3 bucket for uploads"
    Value: !Ref UploadBucket
  FileMetadataTableName:
    Description: "Name of the DynamoDB table for metadata"
    Value: !Ref FileMetadataTable
